### ISSUE TITLE
Doesn't work on Windows 7 64bit

### ISSUE THREAD

**Issue by zNoobs** [itsabhiaryan/TextureUnPacker#1]
Hello, both version 1.2 and 1.3 don't work on my OS, the windows is showing 0.5sec and disappears... :(

**Comment by itsabhiaryan** [comment]
@zNoobs Have you tried to run from [Command Prompt (cmd):](https://en.wikipedia.org/wiki/Cmd.exe).

`java.exe -jar TextureUnPacker.jar`

**Comment by zNoobs** [comment]
It was my config, opengl was not configured correctly, now it works!
Thanks!
